version: '3'
volumes:
  mas-frontend-data:
  mas-elasticsearch-data:
  mas-redis-data:
services:
  mas-frontend:
    image: 'mas:latest'
    build: .
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - NODE_ENV=production
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: yarn run start-frontend
    ports:
      - '80:3200'
      - '443:3201'
    volumes:
      - mas-frontend-data:/data
  mas-loopback:
    image: 'mas:latest'
    build: .
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - NODE_ENV=production
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: yarn run start-loopback
  mas-irc:
    image: 'mas:latest'
    build: .
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - NODE_ENV=production
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: yarn run start-irc
  mas-irc-scktmgr:
    image: 'mas:latest'
    build: .
    depends_on:
      - elasticsearch
      - redis
    environment:
      - NODE_ENV=production
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: yarn run start-irc-scktmgr
    ports:
      - '113:113'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    volumes:
      - mas-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'
  elasticsearch-head:
    image: 'mobz/elasticsearch-head:5'
    ports:
      - '127.0.0.1:9100:9100'
  redis:
    image: 'redis:4.0.8'
    volumes:
      - mas-redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --appendonly yes --save 600 1 --save 300 10 --save 60 10000
